<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<PropertyGroup>
		<Title>Ambient Engine ~ Backend</Title>
		<Authors>MedwardR</Authors>
		<RepositoryUrl>https://github.com/MedwardR/Ambient/</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Ambient.Backend\Ambient.Backend.csproj" />
	</ItemGroup>

</Project>
